### ISSUE TITLE
setBackgroundColor() doesn't work.

### ISSUE THREAD

**Issue by BonnieDoug** [naitsirch/tcpdf-extension#10]
It appears no matter what properties you enter into setBackgroundColor() the result is a great load of nothing... Up to now I've tried 
```
     //Hex
     $table->newRow()->newCell()->setBackgroundColor("#222");
     $table->newRow()->newCell()->setBackgroundColor("#222222");
     $table->newRow()->newCell()->setBackgroundColor("222222");
     $table->newRow()->newCell()->setBackgroundColor(222222);
     //RGB
     $table->newRow()->newCell()->setBackgroundColor(125,125,125);
     $table->newRow()->newCell()->setBackgroundColor(array(125,125,125));
```

All to no avail, the function certainly exists. Along with some documentation specifying it's use. I have tried using a background image for this, however as I will never really know the full height/width of each cell this becomes an issue as there doesn't seem to be an option for stretching the image. As a work around I've started supplying a full height half width image, but this obviously isn't the most ideal solution. 

Any ideas are more than welcomed. If it involves working on the library implementation itself I'm happy to give it a shot, however I feel I would probably need some direction.

**Comment by Always666** [comment]
try

$table->newRow()->newCell()->setFill(true)->setBackgroundColor(array(125,125,125));

**Comment by BonnieDoug** [comment]
That's the one, must be the only combination I didn't try. Thank you.

**Comment by naitsirch** [comment]
Yeah, this is an open request and has already been meantioned in #7.

**Comment by naitsirch** [comment]
This is implemented now ;)
It is easy as this:

```php
$table
    ->newRow()
        ->newCell('Last Name')
            ->setBackgroundColor('#ff4400')                 // hexadecimal RGB color code
            ->setBackgroundColor(array(250, 80, 10))        // decimal RGB color array
        ->end()
    ->end()
```
