### ISSUE TITLE
cell setBackgroundColor doesn't work and a couple other minor things

### ISSUE THREAD

**Issue by starshine531** [naitsirch/tcpdf-extension#7]
1) I noticed in `Cell.php` there's a function called `setBackgroundColor()`.  This is exactly what I need to do, but it does not work.  I realize that I could use a solid color background image to do the same thing, but I'm trying to keep the size of the pdfs generated as small as possible as I hope to be able to keep them email-able size and they may end up being several pages. The use case is that the table rows need to have alternating rows with white and (slightly) grey backgrounds.  Is this not supported?

2) Part of my code needs to take a variable number of data records in an array and create table rows with them, so I'll need to create rows with a `foreach` loop.  I'm rather new to the command chaining syntax, so it's not obvious how to do this.  Could you update the documentation showing a simple example of how to create rows and cells dynamically in a `foreach` loop? Perhaps with the first (header) row outside of the loop?

3) It would be really great if you could include a brief statement in the documentation how to install your extension if composer is not available. (We don't always get the environment we want to work in)  From what I understand, I essentially have to `require_once` each of the pages in the package.  So far this approach seems to work, but if there's a better way, it would be nice to know.

Thank you so much for your time.

**Comment by naitsirch** [comment]
@starshine531 I don't know when I'll have time to address **1)** but maybe I can help you with **2)** and **3)**:

2) If you want to add rows within a loop, you can try something like this:
```php
use Tcpdf\Extension\Table\Table;

$pdf->AddPage(); // add a new page to the document
$table = new Table($pdf);
foreach ($foo as $bar) {
    $table
        ->newRow()
            ->newCell()
                ->setText($bar)
            ->end()
        ->end()
    ;
}
$table->end(); // this renders the table to the PDF. Don't forget!
```
3) You are right. You can use `require_once` or [`spl_autoload_register`](http://php.net/manual/en/function.spl-autoload-register.php) and pass a closure which loads the sources on demand.

I hope this helps :-)

**Comment by starshine531** [comment]
Yes, that's helpful.  Let me know if you get a chance to fix the setBackgroundColor() function.  After looking at the code it looks like it would be a fairly involved fix.  I would do it myself, but I think you could do it a LOT faster than I could.  
For now, I do have a work around. I'll be using the `Line()` method to draw a background line for each row before (or perhaps after) the table is created.  The possibly tricky part will be calculating how big each row will be vertically.  However, this approach does have the advantage of being able to color the whole row instead of only the cells in the row.  Come to think of it, it would be nice to have some row level options in this extension.  At any rate, this is sufficient for my needs at this point.  Thanks for your help and for making this extension.

**Comment by naitsirch** [comment]
The background thing has been fixed now ;-)

**Comment by starshine531** [comment]
Thanks much for taking care of that. It recently came in really handy. Great timing. :)
