### ISSUE TITLE
infinite loop on creating a table with large text block

### ISSUE THREAD

**Issue by Always666** [naitsirch/tcpdf-extension#9]
Hi there, ive encontered an issue, when creating a pdf with 2 columns 7 rows if one of the rows has a text size greater than the page remaining space / size the class TableConverter.php enters a infinite loop of add page until memory exausted/timeout.
It happens on line 507 it loops adding page but the size of the row ($rowHeights[$r] >= $remainingPlace)  is always bigger than the page remaining space / size.
Values my case before and after a few "$pdf->AddPage();" loops
$rowHeights[$r] = 269.8749999999999
$remainingPlace = 266.0000833333333

**Comment by naitsirch** [comment]
I can reproduce the issue. But it is not easy to fix and as I am working on a complete new PDF library (see [pideph](https://github.com/naitsirch/pideph) it is in a really early state and not usably right now), so I don't want to extend this lib further, as my free time is really rare. I'm sorry.

I have just added a check for the cell's height, that will throw an exception if it exceeds the page height.

So you'll have to check the length of your cells and split them into multiple rows manually.

Btw. regarding the 666 in your nickname: Please watch https://youtu.be/3YU4q7-c4v4 :-)
